parameters:
    kphoen.state_machine.listener.persistence.class: KPhoen\DoctrineStateMachineBehavior\Listener\PersistenceListener
    kphoen.state_machine.listener.injection.class: KPhoen\DoctrineStateMachineBundle\Listener\InjectionListener
    kphoen.state_machine.listener.callbacks.class: KPhoen\DoctrineStateMachineBehavior\Listener\StatefulEntitiesCallbacksListener

services:
    # doctrine listeners
    kphoen.state_machine.listener.persistence:
        class:      %kphoen.state_machine.listener.persistence.class%
        arguments:  [ @kphoen.state_machine.factory ]
        tags:
            - { name: doctrine.event_subscriber }

    kphoen.state_machine.listener.injection:
        class:      %kphoen.state_machine.listener.injection.class%
        arguments:  [ @kphoen.state_machine.factory ]
        tags:
            - { name: doctrine.event_subscriber }
            - { name: jms_serializer.event_listener, event: serializer.post_deserialize, method: onPostDeserialize }

    # finite listeners
    kphoen.state_machine.listener.callbacks:
        class:      %kphoen.state_machine.listener.callbacks.class%
        tags:
            - { name: kernel.event_subscriber }
